spring:
  # Redis 集群
  redis:
    sentinel:
      # sentinel 配置
      master: mymaster
      nodes: 192.168.42.111:26379,192.168.42.112:26379,192.168.42.113:26379
    timeout: 6000
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 5
        max-wait: 6000